### ISSUE TITLE
assertHasColumns and assertCanFillables not strict

### ISSUE THREAD

**Issue by rabrowne85** [codenco-dev/eloquent-model-tester#15]
When using the functions `assertHasColumns()` and `assertCanFillables()` the tests are not "strict", in that additional columns in the database table or `$fillable` array will not fail the assertion. As such additional columns in the table structure would slip through. Likewise if a field that shouldn't be fillable will not be caught by this assertion.

I suggest that either new functions are added or the existing ones modified to make them strict by using the `assetEqualsCanonicalizing()` from phpunit.

For example, replacing the existing functions:
```php
    public function assertHasColumns(array|string ...$columns): self
    {
        $columns = $this->getArrayParameters(...$columns);

        $this->assertEqualsCanonicalizing($columns,Schema::getColumnListing($this->getTable()));

        return $this;
    }

    public function assertCanFill(array|string ...$columns):self {
        $columns = $this->getArrayParameters(...$columns);
        $modelClass = $this->getModel();
        $modelObject = new $modelClass;

        $this->assertEqualsCanonicalizing($columns, $modelObject->getFillable());

        return $this;
    }
```

This will assert that the columns are exactly the same as opposed to just checking that the keys exist. I feel this is more "expected behaviour".

Happy to create a pull request, just need to know whether to replace the existing functions or add new.

**Comment by domthomas-dev** [comment]
Hi,

I think it' a good idea, but the better way will be to create new functions.
For example : 
```
public function assertHasOnlyColumns(array|string ...$columns): self
    {
     ...
    }

public function assertDoesntHaveColumns(array|string ...$columns): self
    {
     ...
    }
```

For the `assertCanFill` it's much complicated, because a field can be fill when you use `$guarded = []` for example.
I think `assertCanFill` should use `$modelObject->isFillable($name)` and not getFillable
To test the fillable,  we can create this : 
```
public function assertHasColumnsInFillable(array|string ...$columns): self
    {
     ...
    }

public function assertHasOnlyColumnsInFillable(array|string ...$columns): self
    {
     ...
    }
```

**Comment by rabrowne85** [comment]
That all sounds good to me.

I also noticed that there's a few assertions that use the `assertHasColumns()` as it's basis i.e. `assertHasTimestamps()`.

For `assertHasOnlyColumns()` this is basically asserting that the array provided matches the table columns exactly? i.e. `assetEqualsCanonicalizing()` from my original post?

For the `assertDoesntHaveColumns()` this works as the opposite to the current `assertHasColumns()` in that it confirms that the array of items are not present in the table columns?

You make a good point about the `$guarded`. There is an equivalent `$model->getGuarded()` to return the array set in the model. We could do an intersection (conditionally) of the `$guarded` and `$fillable` arrays to ensure that only the fields specified are fillable/un-guarded. I'm also feeling that we expand and add checks for the `assertHasColumnsInGuarded` etc. - feels like an obvious expansion.

I'll start putting these together and make a PR.

**Comment by domthomas-dev** [comment]
> For `assertHasOnlyColumns()` this is basically asserting that the array provided matches the table columns exactly? i.e. `assetEqualsCanonicalizing()` from my original post?
> 
Exactly

> For the `assertDoesntHaveColumns()` this works as the opposite to the current `assertHasColumns()` in that it confirms that the array of items are not present in the table columns?

Exactly, for example with a new feature that it drop a column.

> 
> You make a good point about the `$guarded`. There is an equivalent `$model->getGuarded()` to return the array set in the model. We could do an intersection (conditionally) of the `$guarded` and `$fillable` arrays to ensure that only the fields specified are fillable/un-guarded. I'm also feeling that we expand and add checks for the `assertHasColumnsInGuarded` etc. - feels like an obvious expansion.
> 

I think is better to use `isFillable` or `isGuardableColumn`

> I'll start putting these together and make a PR.

:+1:
