### ISSUE TITLE
problem with assertHasOneRelation

### ISSUE THREAD

**Issue by alri** [codenco-dev/eloquent-model-tester#18]
Hi !
i get this error : 
`Call to undefined method CodencoDev\EloquentModelTester\ModelTester::assertHasOneRelation()`

and my code : 
`    $this->modelTestable(User::class)->assertHasOneRelation(Phone::class);
`

i just see assertHasHasOneRelation method in your code .

**Comment by domthomas-dev** [comment]
Hi,

Thanks for your review.
I corrected the doc.

https://github.com/codenco-dev/eloquent-model-tester#hasone-et-belongsto

The correct name follow this : 
assertHas[**NameOfRelationType**]Relation -> `assertHasHasOneRelation`

**Comment by alri** [comment]
thank you so much
